name: CD
on:
  release:
    types: [created]
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org
          node-version: 18
      - run: npm install
      - run: npm run build:es2015
      - run: npm run build:esm5
      - run: npm run build:cjs
      - run: npm run build:umd
      - run: npm run build:types
      - run: jq 'del(.scripts)' package.json > build/package.json
      - run: npm publish ./build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}